// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file MultiObjectDetectionModelv8.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace ObjectAndPoseDetection.UWP
{
    
    public sealed class MultiObjectDetectionModelv8Input
    {
        public TensorFloat image; // shape(-1,3,416,416)
    }
    
    public sealed class MultiObjectDetectionModelv8Output
    {
        public TensorFloat grid; // shape(-1,160,13,13)
    }
    
    public sealed class MultiObjectDetectionModelv8Model
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<MultiObjectDetectionModelv8Model> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            MultiObjectDetectionModelv8Model learningModel = new MultiObjectDetectionModelv8Model();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<MultiObjectDetectionModelv8Output> EvaluateAsync(MultiObjectDetectionModelv8Input input)
        {
            binding.Bind("image", input.image);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new MultiObjectDetectionModelv8Output();
            output.grid = result.Outputs["grid"] as TensorFloat;
            return output;
        }

        public async Task<MultiObjectDetectionModelv8Output> EvaluateAsync(ImageFeatureValue image)
        {
            binding.Bind("image", image);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new MultiObjectDetectionModelv8Output();
            output.grid = result.Outputs["grid"] as TensorFloat;
            return output;
        }
    }
}

