// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file SingelObjectApeModelV8.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace ObjectAndPoseDetection.UWP
{
    
    public sealed class SingelObjectApeModelV8Input
    {
        public TensorFloat image; // shape(-1,3,416,416)
    }
    
    public sealed class SingelObjectApeModelV8Output
    {
        public TensorFloat grid; // shape(-1,20,13,13)
    }
    
    public sealed class SingelObjectApeModelV8Model
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<SingelObjectApeModelV8Model> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            SingelObjectApeModelV8Model learningModel = new SingelObjectApeModelV8Model();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model, new LearningModelDevice(LearningModelDeviceKind.DirectXHighPerformance));
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<SingelObjectApeModelV8Output> EvaluateAsync(SingelObjectApeModelV8Input input)
        {
            binding.Bind("image", input.image);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new SingelObjectApeModelV8Output();
            output.grid = result.Outputs["grid"] as TensorFloat;
            return output;
        }
    }
}

